/**
 * decompose-to-ui-kit — agent tool that emits a ui_kits/<slug>/ folder
 * from the current artifact's source. Decomposition itself is prompt-driven
 * (the model decides component boundaries from its read of index.html);
 * this tool only persists the structured plan to the virtual fs.
 *
 * Output:
 *   ui_kits/<slug>/index.html        page-level HTML, parity-matched to source
 *   ui_kits/<slug>/components/*.tsx  reusable components, typed props
 *   ui_kits/<slug>/tokens.css        extracted color/spacing/typography vars
 *   ui_kits/<slug>/manifest.json     schemaVersion + component / token summary
 *   ui_kits/<slug>/README.md         handoff notes for downstream coding agent
 */

import type { AgentTool, AgentToolResult } from '@mariozechner/pi-agent-core';
import { Type } from '@sinclair/typebox';
import { type CoreLogger, NOOP_LOGGER } from '../logger.js';
import type { TextEditorFsCallbacks } from './text-editor';

const ComponentSpec = Type.Object({
  name: Type.String(),
  filename: Type.String(),
  source: Type.String(),
  propsSummary: Type.Optional(Type.String()),
});

const TokenSpec = Type.Object({
  name: Type.String(),
  value: Type.String(),
  category: Type.Union([
    Type.Literal('color'),
    Type.Literal('spacing'),
    Type.Literal('typography'),
    Type.Literal('radius'),
    Type.Literal('shadow'),
  ]),
});

const DecomposeParams = Type.Object({
  slug: Type.String(),
  indexHtml: Type.String(),
  components: Type.Array(ComponentSpec),
  tokens: Type.Array(TokenSpec),
  readmeNotes: Type.Optional(Type.String()),
});

type ComponentSpecT = {
  name: string;
  filename: string;
  source: string;
  propsSummary?: string;
};

type TokenCategory = 'color' | 'spacing' | 'typography' | 'radius' | 'shadow';

type TokenSpecT = {
  name: string;
  value: string;
  category: TokenCategory;
};

export interface DecomposeDetails {
  slug: string;
  componentCount: number;
  tokenCount: number;
  outputPaths: string[];
}

const SCHEMA_VERSION = 1;

function sanitizeSlug(slug: string): string {
  return (
    slug
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '') || 'untitled'
  );
}

function renderTokensCss(tokens: TokenSpecT[]): string {
  const grouped: Record<string, TokenSpecT[]> = {};
  for (const t of tokens) {
    const bucket = grouped[t.category] ?? [];
    bucket.push(t);
    grouped[t.category] = bucket;
  }
  const lines: string[] = [':root {'];
  for (const [category, items] of Object.entries(grouped)) {
    lines.push(`  /* ${category} */`);
    for (const t of items) {
      const name = t.name.startsWith('--') ? t.name : `--${t.name}`;
      lines.push(`  ${name}: ${t.value};`);
    }
  }
  lines.push('}');
  return `${lines.join('\n')}\n`;
}

function renderManifest(slug: string, components: ComponentSpecT[], tokens: TokenSpecT[]): string {
  const tokenCounts: Record<string, number> = {};
  for (const t of tokens) {
    tokenCounts[t.category] = (tokenCounts[t.category] ?? 0) + 1;
  }
  const manifest = {
    schemaVersion: SCHEMA_VERSION,
    generator: 'open-codesign decompose_to_ui_kit',
    generatedAt: new Date().toISOString(),
    slug,
    components: components.map((c) => c.name),
    tokens: tokenCounts,
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function renderReadme(
  slug: string,
  components: ComponentSpecT[],
  notes: string | undefined,
): string {
  const lines: string[] = [
    `# ${slug}`,
    '',
    'Generated by open-codesign `decompose_to_ui_kit`. Drop this folder into your project; a coding agent (Claude Code, Cursor, etc.) can read this README + manifest.json and integrate the components into your existing codebase.',
    '',
    '## Files',
    '- `index.html` — page-level HTML, visually parity-matched to the source',
    '- `components/*.tsx` — reusable React components with typed props',
    '- `tokens.css` — design tokens (colors, spacing, typography, etc.)',
    '- `manifest.json` — machine-readable summary',
    '',
    '## Components',
  ];
  if (components.length === 0) {
    lines.push('_(none extracted)_');
  } else {
    for (const c of components) {
      const summary = c.propsSummary ? ` — ${c.propsSummary}` : '';
      lines.push(`- **${c.name}** (\`components/${c.filename}\`)${summary}`);
    }
  }
  if (notes?.trim()) {
    lines.push('', '## Notes', notes.trim());
  }
  return `${lines.join('\n')}\n`;
}

export function makeDecomposeToUiKitTool(
  fs: TextEditorFsCallbacks | undefined,
  logger: CoreLogger = NOOP_LOGGER,
): AgentTool<typeof DecomposeParams, DecomposeDetails> {
  return {
    name: 'decompose_to_ui_kit',
    label: 'Decompose to UI Kit',
    description:
      'Decompose the current artifact into a ui_kits/<slug>/ folder structure ' +
      '(index.html + components/*.tsx + tokens.css + manifest.json + README.md), ' +
      'shaped for handoff to a downstream coding agent (Claude Code, Cursor). ' +
      'Use ONLY when the user explicitly asks for a coding-agent-ready bundle. ' +
      'Decomposition is one cognitive act: emit ALL components + tokens + manifest in a single tool call. ' +
      'Do NOT split across multiple calls — the model is bad at coordinating state across tool invocations.',
    parameters: DecomposeParams,
    async execute(_toolCallId, params, _signal): Promise<AgentToolResult<DecomposeDetails>> {
      const slug = sanitizeSlug(params.slug);
      const base = `ui_kits/${slug}`;
      const written: string[] = [];
      const startedAt = Date.now();
      const components = params.components as ComponentSpecT[];
      const tokens = params.tokens as TokenSpecT[];

      if (fs !== undefined) {
        await fs.create(`${base}/index.html`, params.indexHtml);
        written.push(`${base}/index.html`);

        for (const comp of components) {
          const path = `${base}/components/${comp.filename}`;
          await fs.create(path, comp.source);
          written.push(path);
        }

        const tokensCss = renderTokensCss(tokens);
        await fs.create(`${base}/tokens.css`, tokensCss);
        written.push(`${base}/tokens.css`);

        const manifest = renderManifest(slug, components, tokens);
        await fs.create(`${base}/manifest.json`, manifest);
        written.push(`${base}/manifest.json`);

        const readme = renderReadme(slug, components, params.readmeNotes);
        await fs.create(`${base}/README.md`, readme);
        written.push(`${base}/README.md`);
      }

      logger.info('[decompose_to_ui_kit] step=ok', {
        slug,
        components: components.length,
        tokens: tokens.length,
        files: written.length,
        ms: Date.now() - startedAt,
      });

      const componentNames =
        components.length > 0 ? components.map((c) => c.name).join(', ') : '(none)';
      const categoryCount = new Set(tokens.map((t) => t.category)).size;

      return {
        content: [
          {
            type: 'text',
            text:
              `Decomposed into ${written.length} files under ${base}/. ` +
              `Components: ${componentNames}. ` +
              `Tokens: ${tokens.length} extracted across ${categoryCount} categor${categoryCount === 1 ? 'y' : 'ies'}.`,
          },
        ],
        details: {
          slug,
          componentCount: components.length,
          tokenCount: tokens.length,
          outputPaths: written,
        },
      };
    },
  };
}
